[project]
name = 'stacks_010_impl'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.SIP_O10]
path = 'contracts/SIP_O10.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
